[global]
overload_tap_timeout = 200

[ids]
*

[main]
capslock = overload(nordic_layer, rightalt) 
leftmeta = overload(meta, macro(leftmeta+d)) 

[nordic_layer]

# CapsLock + a = å (Compose, a, a) - Standard sequence for a-ring
a = macro(rightalt a a)

# CapsLock + e = æ (Compose, a, e) - Standard sequence for ae-ligature
e = macro(rightalt a e)

# CapsLock + o = ø (Compose, o, /) - Standard sequence for o-slash
o = macro(rightalt o slash)
