#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5
filetype="$( file -Lb --mime-type "$file")"

if [[ "$filetype" =~ ^image ]]; then
    chafa "$1" -f sixel -s "$(($2-2))x$3"
    exit 0
fi

if [[ "$filetype" =~ ^video ]]; then
    # vidthumb is from here:
    # https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
    v=`vidthumb "$file"`
    chafa "$v" -f sixel -s "$(($2-2))x$3"
    exit 0
fi

pistol "$file"
exit 0
