#!/bin/sh

case "$(file -Lb --mime-type -- "$1")" in
    image/*)
        chafa -f sixel -s "$2x$3" --animate off --polite on "$1"
        exit 0
        ;;
    video/*)
        # vidthumb is from here:
        # https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
        chafa -f sixel -s "$2x$3" --animate off --polite on `vidthumb "$1"` 
        exit 0
        ;;
    *)
        pistol "$1"
        ;;
esac
