config_version = 14

[audio]
enable_sounds = true
sound_volume = 0.99999997764825821

[backdrop]
blur_intensity = 0.20999999530613422
enabled = true
tint_intensity = 0.63999998569488525

[bar.default]
background_opacity = 0.63999998569488525
capsule_fill = "#20508B"
end = [
    "media",
    "tray",
    "recorder",
    "bluetooth",
    "input_volume",
    "volume",
    "brightness",
    "battery",
    "network",
    "notifications"
]
margin_edge = 0.0
margin_ends = 0.0
padding = 6
radius = 0
shadow = false
start = [ "session", "launcher", "workspaces" ]
widget_spacing = 4

[control_center.calendar]
show_events_card = false

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[desktop_widgets]
enabled = false

[dock]
monitors = [ "DP-1" ]

[location]
address = "Oslo, Norway"

[lockscreen]
blur_intensity = 0.18999999575316906
fingerprint = false
lock_on_startup = true
monitors = [ "DP-1" ]
tint_intensity = 0.65999998524785042

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@winit",
    "lockscreen-login-box@DP-1",
    "lockscreen-login-box@DP-2",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000002"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 759.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 752.0
    output = "DP-2"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "on_primary"
        background_opacity = 0.0
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 196.0
    box_width = 810.0
    cx = 1278.0
    cy = 1275.0
    output = "winit"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 144.0
    box_width = 304.0
    cx = 1280.0
    cy = 240.0
    output = "DP-2"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        clock_style = "digital"
        font_family = "FiraCode Nerd Font"
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 1280.0
    cy = 542.0
    output = "DP-2"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "sticker"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false
        image_path = "/home/meta/Pictures/A0007.png"
        opacity = 1.0

[notification]
layer = "overlay"
monitors = [ "DP-1" ]

[osd]
background_opacity = 0.99999997764825821
lock_keys = false
monitors = [ "DP-1" ]
offset_x = 0
orientation = "vertical"
position = "top_right"
position_vertical = "center_right"

    [osd.kinds]
    media = false
    volume_input = false

[plugin_settings."noctalia/screen_recorder"]
audio_source = "default_output"
video_codec = "av1"
video_source = "portal"

[plugins]
enabled = [ "noctalia/screen_recorder" ]

[shell]
avatar_path = "/home/meta/Pictures/sly.png"
clipboard_auto_paste = "off"
password_style = "random"
polkit_agent = true
settings_show_advanced = true

    [shell.animation]
    speed = 4.0

    [shell.launcher]
    categories = false

    [shell.panel]
    borders = false
    launcher_categories = false
    open_near_click_control_center = true
    transparency_mode = "soft"

    [shell.screen_corners]
    enabled = true

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    shortcut = "q"
    variant = "default"

    [[shell.session.actions]]
    action = "suspend"
    enabled = true
    shortcut = "s"
    variant = "primary"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    shortcut = "r"
    variant = "destructive"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    shortcut = "u"
    variant = "destructive"

    [[shell.session.actions]]
    action = "lock"
    command = "hyprlock"
    enabled = true
    shortcut = "l"
    variant = "default"

[system.monitor]
enabled = false

[theme]
builtin = "Nord"
community_palette = "GruvboxAlt"
mode = "dark"
wallpaper_scheme = "vibrant"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "qt" ]
    community_ids = [ "zathura" ]

[wallpaper]
directory = "/home/meta/Pictures/walls"

    [wallpaper.default]
    path = "/home/meta/Pictures/walls/bg.png"

    [wallpaper.last]
    path = "/home/meta/Pictures/walls/bg.png"

    [wallpaper.monitors.DP-1]
    path = "/home/meta/Pictures/walls/bg.png"

    [wallpaper.monitors.DP-2]
    path = "/home/meta/Pictures/walls/bg.png"

[weather]
address = "Oslo, Norway"

[widget.1]
length = 10.0
type = "spacer"

[widget.battery]
device = "/org/freedesktop/UPower/devices/battery_BAT0"
display_mode = "graphic"
hide_when_full = true

[widget.bongocat]
script = "scripts/bongocat.lua"
type = "scripted"

[widget.brightness]
show_label = false

[widget.clock]
format = "{:%a %B %d, %H:%M}"

[widget.input_volume]
capsule = true
capsule_opacity = 0.0
capsule_padding = 0.0
mute_color = "error"
show_label = false

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.tray]
drawer = true

[widget.volume]
mute_color = "error"

[widget.workspaces]
hide_when_empty = true